export const categories = [
  "Electronics",
  "Sound",
  "Cameras",
  "Lighting",
  "Grip",
  "Special Effects",
  "Dolly & Crane",
  "Staging & Construction",
  "Recording & Playback",
  "Post-Production",
  "Visual Effects",
  "Camera Support",
  "Power and Electrical",
  "Transportation & Logistics",
  "Film Stock & Digital Media",
  "Safety",
  "Specialty",
  "Production Office",
  "Prop & Wardrobe",
  "Rental and Leasing"
]
export const fieldofstudyOptions = [
    "General Agriculture",
    "Agribusiness Operations",
    "Agricultural Business & Management",
    "Agricultural Economics",
    "Agricultural Mechanization",
    "Agricultural Production",
    "Agronomy & Crop Science",
    "Animal Sciences",
    "Food Sciences & Technology",
    "Horticulture Operations & Management",
    "Horticulture Science",
    "Natural Resources Conservation, General",
    "Environmental Science",
    "Forestry",
    "Natural Resources Management",
    "Wildlife & Wildlands Management",
    "General Architecture",
    "Architectural Environmental Design",
    "City/Urban/Regional Planning",
    "Interior Architecture",
    "Landscape Architecture",
    "General Area Studies",
    "Asian Area Studies",
    "European Area Studies",
    "Latin American Area Studies",
    "North American Area Studies",
    "General Ethnic & Minority Studies",
    "African American Studies",
    "American Indian/Native American Studies",
    "Latino/Chicano Studies",
    "Women’s Studies",
    "Liberal Arts & General Studies",
    "Library Science",
    "Multi/Interdisciplinary Studies",
    "General Art",
    "Art History, Criticism & Conservation",
    "Fine/Studio Arts",
    "Cinema/Film",
    "Cinematography/Film/Vide Production",
    "Dance",
    "General Design & Visual Communications",
    "Fashion/Apparel Design",
    "Graphic Design",
    "Industrial Design",
    "Interior Design",
    "Music, General",
    "Music, Performance",
    "Music, Theory & Composition",
    "Photography",
    "Theatre Arts/Drama",
    "Accounting",
    "Accounting Technician",
    "General Business Administration & Management",
    "Hotel/Motel Management",
    "Human Resources Development/Training",
    "Human Resources Management",
    "International Business Management",
    "Labor/Industrial Relations",
    "Logistics & Materials Management",
    "Marketing Management & Research",
    "Office Supervision & Management",
    "Operations Management & Supervision",
    "Organizational Behavior",
    "Purchasing/Procurement/Contracts Management",
    "Restaurant/Food Services Management",
    "Small Business Management/Operations",
    "Travel/Tourism Management",
    "Business/Management Quantitative Methods",
    "Actuarial Science",
    "Business/Managerial Economics",
    "General Finance",
    "Banking & Financial Support Services",
    "Financial Planning & Services",
    "Insurance & Risk Management",
    "Investments & Securities",
    "Management Information Systems",
    "Real Estate",
    "General Sales, Merchandising, & Marketing",
    "Fashion Merchandising",
    "Tourism & Travel Marketing",
    "Secretarial Studies & Office Administration",
    "General Communications",
    "Advertising",
    "Digital Communications/Media",
    "Journalism, Broadcast",
    "Journalism, Print",
    "Mass Communications",
    "Public Relations & Organizational Communication",
    "Radio & Television Broadcasting",
    "General Communications Technology",
    "Graphic & Printing Equipment Operation",
    "Multimedia/Animation/Special Effects",
    "Radio & Television Broadcasting Technology",
    "General Family & Consumer Sciences",
    "Adult Development & Aging/Gerontology",
    "Child Care Services Management",
    "Child Development",
    "Consumer & Family Economics",
    "Food & Nutrition",
    "Textile & Apparel",
    "General Parks, Recreation, & Leisure",
    "Exercise Science/Physiology/Kinesiology",
    "Health & Physical Education/Fitness",
    "Parks/Rec/Leisure Facilities Management",
    "Sport & Fitness Administration/Management",
    "Personal Services, General",
    "Cosmetology/Hairstyling",
    "Culinary Arts/Chef Training",
    "Funeral Services & Mortuary Science",
    "General Protective Services",
    "Corrections",
    "Criminal Justice",
    "Fire Protection & Safety Technology",
    "Law Enforcement",
    "Military Technologies",
    "General Public Administration & Services",
    "Community Organization & Advocacy",
    "Public Administration",
    "Public Affairs & Public Policy Analysis",
    "Social Work",
    "General Computer & Information Sciences",
    "Computer Networking/Telecommunications",
    "Computer Science & Programming",
    "Computer Software & Media Applications",
    "Computer System Administration",
    "Data Management Technology",
    "Information Science",
    "Webpage Design",
    "Mathematics, General",
    "Applied Mathematics",
    "Statistics",
    "Counseling & Student Services",
    "Educational Administration",
    "Special Education",
    "General Teacher Education",
    "Curriculum & Instruction",
    "Early Childhood Education",
    "Elementary Education",
    "Junior High/Middle School Education",
    "Postsecondary Education",
    "Secondary Education",
    "Teacher Assisting/Aide Education",
    "Teacher Education, Subject-Specific",
    "Agricultural Education",
    "Art Education",
    "Business Education",
    "Career & Technical Education",
    "English-as-a-Second-Language Education",
    "English/Language Arts Education",
    "Foreign Languages Education",
    "Health Education",
    "Mathematics Education",
    "Music Education",
    "Physical Education & Coaching",
    "Science Education",
    "Social Studies/Sciences Education",
    "General Engineering",
    "Aerospace/Aeronautical Engineering",
    "Agricultural/Bioengineering",
    "Architectural Engineering",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Engineering",
    "Construction Engineering/Management",
    "Electrical, Electronics & Communications Engineering",
    "Environmental Health Engineering",
    "Industrial Engineering",
    "Mechanical Engineering",
    "Nuclear Engineering",
    "Drafting/CAD Technology, General",
    "Architectural Drafting/CAD Technology",
    "Mechanical Drafting/CAD Technology",
    "General Engineering Technology",
    "Aeronautical/Aerospace Engineering Technologies",
    "Architectural Engineering Technology",
    "Automotive Engineering Technology",
    "Civil Engineering Technology",
    "Computer Engineering Technology",
    "Construction/Building Technology",
    "Electrical, Electronics Engineering Technologies",
    "Electromechanical/Biomedical Engineering Technologies",
    "Environmental Control Technologies",
    "Industrial Production Technologies",
    "Mechanical Engineering Technology",
    "Quality Control & Safety Technologies",
    "Surveying Technology",
    "General English Language & Literature",
    "American/English Literature",
    "Creative Writing",
    "Public Speaking",
    "General Foreign Languages/Literatures",
    "Asian Languages & Literatures",
    "Classical/Ancient Languages & Literatures",
    "Comparative Literature",
    "French Language & Literature",
    "German Language & Literature",
    "Linguistics",
    "Middle Eastern Languages & Literatures",
    "Spanish Language & Literature",
    "General Health Services Administration",
    "Hospital/Facilities Administration",
    "Medical Office/Secretarial",
    "Medical Records",
    "General Medical/Clinical Assisting",
    "Dental Assisting",
    "Medical Assisting",
    "Occupational Therapy Assisting",
    "Physical Therapy Assisting",
    "Veterinarian Assisting/Technology",
    "Chiropractic",
    "Dental Hygiene",
    "Dentistry",
    "Emergency Medical Technology",
    "General Health-Related Professions & Services",
    "Athletic Training",
    "Communication Disorder Services",
    "Public Health",
    "General Health/Medical Technology",
    "Medical Laboratory Technology",
    "Medical Radiologic Technology",
    "Nuclear Medicine Technology",
    "Respiratory Therapy Technology",
    "Surgical Technology",
    "Medicine",
    "Nursing, Practical/Vocational",
    "Nursing, Registered",
    "Optometry",
    "Osteopathic Medicine",
    "Pharmacy",
    "Physician Assisting",
    "General Therapy & Rehabilitation",
    "Alcohol/Drug Abuse Counseling",
    "Massage Therapy",
    "Mental Health Counseling",
    "Occupational Therapy",
    "Physical Therapy",
    "Psychiatric/Mental Health Technician",
    "Rehabilitation Therapy",
    "Vocational Rehabilitation Counseling",
    "Veterinary Medicine",
    "Philosophy",
    "Religion",
    "Theology, General",
    "Bible/Biblical Studies",
    "Divinity/Ministry",
    "Religious Education",
    "General Aviation & Airway Science",
    "Aircraft Piloting & Navigation",
    "Aviation Management & Operations",
    "Construction Trades",
    "General Mechanics & Repairers",
    "Aircraft Mechanics/Technology",
    "Autobody Repair/Technology",
    "Automotive Mechanics/Technology",
    "Avionics Technology",
    "Diesel Mechanics/Technology",
    "Electrical/Electronics Equip Installation & Repair",
    "Heating/Air Cond/Refrig Install/Repair",
    "Precision Production Trades, General",
    "Machine Tool Technology",
    "Welding Technology",
    "Transportation & Materials Moving",
    "General Biology",
    "Biochemistry & Biophysics",
    "Cell/Cellular Biology",
    "Ecology",
    "Genetics",
    "Marine/Aquatic Biology",
    "Microbiology & Immunology",
    "Zoology",
    "General Physical Sciences",
    "Astronomy",
    "Atmospheric Sciences & Meteorology",
    "Chemistry",
    "Geological & Earth Sciences",
    "Physics",
    "General Legal Studies", 
    "Court Reporting",
    "Law",
    "Legal Administrative Assisting/Secretarial",
    "Paralegal/Legal Assistant",
    "General Social Sciences",
    "Anthropology",
    "Criminology",
    "Economics",
    "Geography",
    "History",
    "International Relations & Affairs",
    "Political Science & Government",
    "Psychology, Clinical & Counseling",
    "General Psychology",
    "Sociology",
    "Urban Studies/Urban Affairs"
  ];
  export const educationlevelOptions = [
    "Not Educated",
    "Elementary School Level",
    "High School Level",
    "College Level",
    "University Level",
    "Bachelor's degree",
    "Post Bachelor Level",
    "Masters Degree",
    "Post Masters Level",
    "Doctorate Degree",
    "Post Doctorate Level",
    "Proffesor Degree"
  ]

  export const countriesOptions = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Colombia",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic (the)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
];
export const languagesOptions = [
"Afrikaans",
"Albanian",
"Arabic",
"Armenian",
"Basque",
"Bengali",
"Bulgarian",
"Catalan",
"Cambodian",
"Chinese",
"Croatian",
"Czech",
"Danish",
"Dutch",
"English",
"Estonian",
"Fiji",
"Finnish",
"French",
"Georgian",
"German",
"Greek",
"Gujarati",
"Hebrew",
"Hindi",
"Hungarian",
"Icelandic",
"Indonesian",
"Irish",
"Italian",
"Japanese",
"Javanese",
"Korean",
"Latin",
"Latvian",
"Lithuanian",
"Macedonian",
"Malay",
"Malayalam",
"Maltese",
"Maori",
"Marathi",
"Mongolian",
"Nepali",
"Norwegian",
"Persian",
"Polish",
"Portuguese",
"Punjabi",
"Quechua",
"Romanian",
"Russian",
"Samoan",
"Serbian",
"Slovak",
"Slovenian",
"Spanish",
"Swahili",
"Swedish",
"Tamil",
"Tatar",
"Telugu",
"Thai",
"Tibetan",
"Tonga",
"Turkish",
"Ukrainian",
"Urdu",
"Uzbek",
"Vietnamese",
"Welsh",
"Xhosa"
];